package finalthing;

import java.io.BufferedReader;
import java.io.BufferedWriter;
//import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

public class filethingy extends javax.swing.JFrame {

    /**
     * Creates new form filethingy
     */
    public filethingy() {
        initComponents();
        this.toFront();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Open");
        setType(java.awt.Window.Type.POPUP);

        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        
        //if there is no file selected, just return to the home window
        if(jFileChooser1.getSelectedFile() == null){        
            hoem h = new hoem();
            h.setVisible(true);
            this.setVisible(false);
        }
        else{
            String file = jFileChooser1.getSelectedFile().toString();
            //split the full filepath around periods to get the file extension
            //the two backwards slashes are to get around regex shenanigans
            String[] splitfile = file.split("\\.");
            //System.out.println(Arrays.toString(splitfile));
            int conf = 0;
            //if the file extension (the last item when split around periods) is NOT one recognised
            if(!(splitfile[splitfile.length-1].equals("txt")
                    || splitfile[splitfile.length-1].equals("csv")
                    || splitfile[splitfile.length-1].equals("gss"))){
                conf = JOptionPane.showConfirmDialog(rootPane, "Unsupported file type\nOpen anyway?");
                //System.out.println(Integer.toString(conf));
            }
            //2 = Cancel
            if(conf == 2){
                hoem h = new hoem();
                h.setVisible(true);
                this.setVisible(false);
            }
            //0 = Yes
            if(conf == 0){
                //boolean done;
                //array where each entry in the recent file is placed, to be rearranged upon opening a new one
                String[] queue = new String[20];
                int count = 0;
                FileWriter fw = null;
                FileReader fr = null;
                try {
                    fr = new FileReader("recent");
                    BufferedReader br = new BufferedReader(fr);
                    String line;
                    while((line = br.readLine()) != null && count < 19){
                        //counts the index of queue which each entry should be placed at
                        count++;
                        //add any item from recent into queue as long as it isn't the one being opened
                        if(!(line.equals(jFileChooser1.getSelectedFile().toString()))){
                            queue[count] = line;
                        }
                    }
                    br.close();
                    fr.close();
                    fw = new FileWriter("recent");
                    BufferedWriter bw = new BufferedWriter(fw);
                    //write the file being opened first, so it's at the start of the list
                    bw.write(jFileChooser1.getSelectedFile().toString()+"\n");
                    //then everything else
                    for(int i=0; i<queue.length; i++){
                        if(!(queue[i] == null)){
                            bw.write(queue[i]+"\n");
                        }
                    }
                    bw.close();
                    fw.close();
                } 
                catch (IOException ex) {
                    System.out.println("could not update recent file");
                }

                editorg e = new editorg(jFileChooser1.getSelectedFile().toString());
                e.setVisible(true);
                this.setVisible(false);
            }
            //just do nothing if the user says No (1) or closes the popup
        }
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(filethingy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(filethingy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(filethingy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(filethingy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new filethingy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
}
